### ISSUE TITLE
Add clan Tags

### ISSUE THREAD

**Issue by din-din** [LastExceed/Exceed#49]
As a Server I want to set a clan-tag to the player so that the players can see in which clans they are

clans should be account-bound and the server should add the clantag to the name to prevent impersonation and allow clanbased rankings and statistics

The story is considered done when a function is implemented which adds a 3 letter Tag to the playername and the playername changes to "[TAG] playername"

**Comment by LastExceed** [comment]
closing due to retirement of the bridge
